AWSTemplateFormatVersion: '2010-09-09'
Description: NDT Trusted account role
Parameters:
  paramTrustedAccount:
    Description: Account to trust in managing permissions for this account
    Type: String
    Default: ""
  paramRoleName:
    Description: Name of the role that gives trust to the trusted account
    Type: String
    Default: ""
Resources:
  TrustRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "trust-${paramTrustedAccount}-${paramRoleName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                !Sub "arn:aws:iam::${paramTrustedAccount}:root"
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AllowAdmin
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action: '*'
              Resource: '*'
Outputs:
  TrustRole:
    Value: !Ref TrustRole
    Export:
      Name:
        Fn::Join: [":", [{Ref: "AWS::StackName"}, TrustRole]]
  TrustedAccount:
    Value: !Ref paramTrustedAccount
    Export:
      Name:
        Fn::Join: [":", [{Ref: "AWS::StackName"}, TrustedAccount]]
